<?php

namespace App\OpenApi;

/**
 * @OA\OpenApi(
 *   @OA\Info(
 *     version="1.0.0",
 *     title="Your API",
 *     description="API documentation generated by l5-swagger"
 *   ),
 *   @OA\Server(
 *     url="/",
 *     description="Current server"
 *   )
 * )
 */
class OpenApi
{
}